=== apoorvasrivastava98/WebTech/Bookstore.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="BOOKSTORE">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="BOOK">
       <xs:complexType>
        <xs:sequence>
         <xs:element name="NAME" type="xs:string"></xs:element>
         <xs:element name="SUBJECT" type="xs:string"></xs:element>
         <xs:element name="AUTHOR" type="xs:string></xs:element>
         <xs:element name="PRICE" type="xs:string"></xs:element>
         <xs:element name="PAGES" type="xs:string"></xs:element>
        </xs:sequence>
       <xs:attribute name="type" type="xs:string"></xs:attribute>
       </xs:complexType>
      </xs:element>
     </xs:sequence>
    </xs:complexType>
   </xs:element>
</xs:schema>

=== apoorvasrivastava98/WebTech/Bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<BOOKSTORE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Bookstore.xsd">

 <BOOK type="Subject Book">
  <NAME>Principles of Web Design</NAME>
  <SUBJECT>WEB Technology</SUBJECT>
  <AUTHOR>Joel Sklar</AUTHOR>
  <PRICE>5000</PRICE>
  <PAGES>500</PAGES>
 </BOOK>
 <BOOK type="Subject Book">
  <NAME>Operating System Concepts</NAME>
  <SUBJECT>OS</SUBJECT>
  <AUTHOR>Silverschatz</AUTHOR>
  <PRICE>2000</PRICE>
  <PAGES>500</PAGES>
 </BOOK>
 <BOOK type="Subject Book">
   <NAME>Operations Research</NAME>
   <SUBJECT>CBOT</SUBJECT>
  <AUTHOR>Taha</AUTHOR>
  <PRICE>3000</PRICE>
  <PAGES>500</PAGES>
  </BOOK>
 <BOOK type="Subject Book">
  <NAME>Introduction to Algorithms</NAME>
  <SUBJECT>DAA</SUBJECT>
  <AUTHOR>Coremen</AUTHOR>
  <PRICE>2000</PRICE>
  <PAGES>500</PAGES>
 </BOOK>
 <BOOK type="Novels">
  <NAME>Harry Potter</NAME>
  <AUTHOR>JK ROWLING</AUTHOR>
  <PRICE>1000</PRICE>
  <PAGES>500</PAGES>
 </BOOK>
 <BOOK type="Novels">
  <NAME>The Lord of Rings</NAME>
  <AUTHOR>JRR Tolkien</AUTHOR>
  <PRICE>2500</PRICE>
  <PAGES>500</PAGES> 
</BOOK>
</BOOKSTORE>
